### ISSUE TITLE
Update Lisa Keys on Progress

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/MileCastles#102]

**Comment by cheapjack** [comment]
Be good to update her with proof of the revised print text @gkboulter 👍

**Comment by gkboulter** [comment]
Latest proofs with revised text from Friday / Monday - can help with update tomorrow @cheapjack 

As pdf (zipped):

[HC Map v11.pdf.zip](https://github.com/cheapjack/MileCastles/files/1052974/HC.Map.v11.pdf.zip)

As jpgs:

![hc map v11 flipped](https://cloud.githubusercontent.com/assets/17590643/26799582/1d3f1b04-4a2e-11e7-910a-fafe3e14f0ab.jpg)
![hc map v11](https://cloud.githubusercontent.com/assets/17590643/26799581/1d3c8196-4a2e-11e7-8ec3-991f9357efd5.jpg)
![hc map v112](https://cloud.githubusercontent.com/assets/17590643/26799583/1d4263d6-4a2e-11e7-8597-558ffa34b4ac.jpg)
