### ISSUE TITLE
USB Leads

### ISSUE THREAD

**Issue by cefn** [cheapjack/MileCastles#113]
You mentioned you might need to source USB leads to fix issues.

I think these leads may have become available once again at CPC (they were previously out of stock)...

https://cpc.farnell.com/webapp/wcs/stores/servlet/ProductDisplay?catalogId=15002&ICID=TREML004-004&langId=69&storeId=10180&krypto=mttNGbkbAj0DLvGLkMtfnm6q8vc2O7jwjIvJny%2Fki6OOV2s0qmhEDSHgg7q7wn51hrDjrGPiaXZP94WuEMBxDhIvJTAWK9nmVgqixgyHeOZ%2FJ%2BMrUojyGF%2F%2FmuWTLVtxc8bbUTsVsnFiCmcVehRCjQ%3D%3D&ddkey=http%3Aen-CPC%2FCPC_United_Kingdom%2Fpro-signal%2Fpsg91156%2Flead-high-retention-usb-a-micro%2Fdp%2FCS28042

This second specification of leads is also available...

http://cpc.farnell.com/pro-signal/cdl-160-3m/lead-usb-a-male-micro-b-male-black/dp/CS29702

**Comment by cheapjack** [comment]
Got some white ones on CPC, slightly cheaper same spec
