### ISSUE TITLE
Install at final three/four sites

### ISSUE THREAD

**Issue by gkboulter** [cheapjack/MileCastles#115]
Just putting this in one place for reference, so I can keep track whilst away.

GB to:
- [x] Send install docs to Frances / Alex / Jane refer to issue #93 
- [x] Send staff guide docs to Frances / Alex / Jane
- [x] Get confirmation from Frances on Corbridge (not Housesteads) for 18th
- [x] Order 800 or  600 new prints for final sites
- [x] Fold 600/800 maps for final sites 
- [x] Finish stickering remaining 800 tags
- [x] Send approved ARBEIA game to @cheapjack
- [x] Wait for approval on (Housesteads not being used) and Segy (due Friday 7th) and check 
- [x] Send approved HSTEADS / SEGY to @cheapjack 
- [x] Confirm times with Corbridge (instead of Housesteads)  and Senhouse for Tues 18th
- [x] Source cordless drill if @cheapjack not able to borrow from Does

@cefn :
- [x] @cefn to collect boxes and all brackets / fixings from @cheapjack 
- [x] @cefn to flash boxes with final games (SENHOUSE / HOUSTEADS / SEGY / ARBEIA)
- [x] Glenn to confirm meet up times for 17th /18th installs with @cefn 
- [x] Glenn and @cefn to install remaining sites on 17th / 18th

and @cheapjack:
- [x] @cheapjack to send game text to Jayne at SENHOUSE for approval
- [x] Arrange pickup of boxes etc. with @cefn 
- [x] Provide cordless drill for @cefn & @gkboulter to borrow
- [x] Sege battery holder as in #63

**Comment by cheapjack** [comment]
Take note of recent comments in issue #114 before re-flashing `corbridge IV`
Drill is from Patrick in DoES so when Ive arranged date to handover boxes to Cefn I will get that drill unless @cefn has his own powerful cordless drill

**Comment by cheapjack** [comment]
updated [milecastles webpage](http://milecastles.uk) to reflect latest install/deinstall
