### ISSUE TITLE
Decide on idle text

### ISSUE THREAD

**Issue by cefn** [cheapjack/MileCastles#30]
Need to figure out what idle text is shown. I am imagining really basic stuff like...

```python
"""
TAP
HERE
"""
```

...or...

```python
"""
TAP HERE
TO PLAY
"""
```

...but we might want something more explanatory for non-players to participate (this text is crap, but is an indication)

```python
"""
TO PLAY, TAP 
YOUR TAG HERE
(FROM SHOP)
"""
```

We could have it alternate between two or more sets of text.

```python
"""
TAP HERE
TO PLAY
""",
"""
TAGS AT
GIFT SHOP
"""
```

I need to know this as I have to choose a pixel font which can make this as big as possible, based on the text chosen. It will of course have to be different from the main text font. 

I have managed to extract at least some of the fonts available from the [U8G2 font set](https://github.com/olikraus/u8g2/wiki/fntlistall).

**Comment by cheapjack** [comment]
We think we could go for alternating between 2 texts; but inversed out as we'd discussed and obviously just on the mains powered boxes
```
"""
USE CARD
TO PLAY
""",

"""
GET CARD
FROM TILL
"""
```
