### ISSUE TITLE
Soft latching circuit

### ISSUE THREAD

**Issue by cefn** [cheapjack/MileCastles#36]
https://www.pololu.com/product/2808 could be a complement for the USB battery pack, preserving power by being triggered by NC (normally closed) reed switch mounted on cover.

**Comment by cheapjack** [comment]
👍

**Comment by cheapjack** [comment]
Include 2 3M mounting holes for the circuit and incorporate reed switch from the breadboard to the outer skin where it would make contact with the mounted swing-cover, the magnet inset on the inside of the lasercut acrylic bent cover via an IP66 grommet
