### ISSUE TITLE
Senhouse Marspoints

### ISSUE THREAD

**Issue by cefn** [cheapjack/MileCastles#73]
Is marspoints redundant? Might be best to remove extra operations/complexity if they are not being used for anything.

**Comment by cheapjack** [comment]
I wanted some variance in battle/ending text originally but not got round to adding that feature yet

**Comment by cheapjack** [comment]
It's not doing an awful lot but just adds texture to the final score so would like to keep it in. Its shorter game than corbridge so maybe not massive issue
