### ISSUE TITLE
Make risk assessments for all the installs

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/MileCastles#77]

**Comment by gkboulter** [comment]
A general risk sheet to cover all sites (indoor and outdoors) here:
[MILECASTLES RISK ASSESSMENT](https://docs.google.com/spreadsheets/d/1_q5nkvIG3mbnqPf6uHtJrUBNY0iSWJ-8bwP5XmgRg4M/edit#gid=746338726)

Will need to add following items to print:
- Choke hazard warning for game tags
- 'Do not run' advice to avoid tripping etc, particularly in outdoor sites

Edits from @cefn and @cheapjack welcome.
