### ISSUE TITLE
Send Ross 4 reed switches and magnets

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/MileCastles#79]
Sorry forgot to pick up this last week can you next day it to DoES for tomorrow Thursday 4th may? http://doesliverpool.com/location

Still in Wales will try catch up later this afternoon if I can :)

**Comment by cefn** [comment]
Hi there. I don't have a supply of the magnets. The one I found was a magnet lying around - was on my fridge.  I have now dispatched the other three I had on my fridge, (which I think are identical) but that leaves you one short.

**Comment by cheapjack** [comment]
Ok have an alternative for that one I think but not as low profile :) ring you soon for update when I can:)
