### ISSUE TITLE
Prepare an issue list for each venue based on the enquiry form

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/MileCastles#9]
Our [initial enquiry form](https://docs.google.com/forms/d/16GssZ3BB9KSyWSL2OuTMu0BvnYdlhS9IDEVNWEgmMPc/edit#responses) has resulted in a few things worth tackling at our first recce meeting.

I'll prep a doc where we can input all this info

**Comment by gkboulter** [comment]
Created a quick summary of site visits with info in where each box will go and issues to resolve for each site:

[(https://docs.google.com/spreadsheets/d/1O9EbYnrRbLq14Vwc4btC5YH3rWIDOSFfX5Bne3iuhpo/edit?usp=sharing)]
