### ISSUE TITLE
Page Sentence continuation in senhouse

### ISSUE THREAD

**Issue by cefn** [cheapjack/MileCastles#92]
Senhouse contains this broken over two pages, which is hard to scan, especially given any delay between rendering the pages. Ideally text like this would be in one page, or at least ellipsis should be used to understand that it's a continuation of the sentence from the previous page.

```"for him. He also helps with
the harvest you know!"

"Which helps us
make more wine!"
```

**Comment by cheapjack** [comment]
changed to 
```
sequence = [
         """LEAVE a cup of wine.
         He also helps with
         the harvest you know...""",
         """...Which helps us
         make more wine!"""
         ],
```
