### ISSUE TITLE
Provide Evidence of Method Statement, Public Liability and Risk Assessment for all the installs

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/MileCastles#93]

**Comment by gkboulter** [comment]
Method Statement for indoor / outdoor installation - will make copies for each site
https://docs.google.com/document/d/1Ya-3x5EehvbWaIwtLodFDF9t9DRvRhA24Bv41bQiGl0/edit?usp=sharing

Risk Assessment for installation and use of boxes:
https://docs.google.com/spreadsheets/d/1_q5nkvIG3mbnqPf6uHtJrUBNY0iSWJ-8bwP5XmgRg4M/edit?usp=sharing

Installation schedule with placement of boxes - dates / times subject https://docs.google.com/spreadsheets/d/1RS41IP_3PRXBTv9ltepXAmKgustCaYeQunNOyuZVeoI/edit?usp=sharing to change
