### ISSUE TITLE
Comment on any issues from the fuzzing

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/MileCastles#94]
Fuzzing emulator great! So good to see actual display, love it! will get it up on @gkboulter laptop in the morning

Some feedback:

- `To begin work go to Box II` 🔪  although it almost fits the final pixles of the I character are missing so look like the numerals are cut off. Fix could be `goto` as in `goto 10`
- `Place Tag Below` ⬛️  think it should be capitalised, in reverse, white on black, maybe centre justified or even same as `Reading tag...` but capitalised
- `but you don't have long to`🔪 final pixel on the right lost in the `o` character, feels like its cut off
- `Reading tag...` 👍 in reverse white on black right justified is bang on, really like it. Wonder if `Place Tag Below` should be the same for consistency?

**Comment by cefn** [comment]
The reason for Place Tag Below being big, is that it's expected to be read as you walk up to it. The remainder are expected to be read as you are directly looking at the screen.
